### PR TITLE
Added core version and small syntax fix. Pulled from https://github.c…

### PR DESCRIPTION
**Pull request by sheydari-ds**
…om/DoSomething/ansible-search without git history.

### CODE REVIEW

**Comment by sergii-tkachenko** [comment]
What's that?

**Comment by sergii-tkachenko** [comment]
Were you looking for https://github.com/DoSomething/tower/tree/master/roles/dosomething.search?

**Comment by sheydari-ds** [comment]
Yeah, that's what I meant.

**Comment by sergii-tkachenko** [comment]
:+1:

**Pull request merged**
