### PR TITLE
Updates Shae's pub key with actual pub key

### PR DESCRIPTION
**Pull request by mshmsh5000**
We had some confusion today about what is Shae's correct RSA pub key. This is the right one!

### CODE REVIEW

**Comment by sergii-tkachenko** [comment]
Are you sure [that's](https://github.com/sbsmith86.keys) not the one?

**Comment by sbsmith86** [comment]
@mshmsh5000 @sergii-tkachenko triple checked this is correct!

**Comment by sergii-tkachenko** [comment]
New Shae's key is added to GitHub: https://github.com/sbsmith86.keys.
👍 :shipit:

**Comment by sergii-tkachenko** [comment]
I'll go ahead and merge this.

**Pull request merged**
