### PR TITLE
Upgrade PHP to 7.0.

### PR DESCRIPTION
**Pull request by sergii-tkachenko**
TBD

### CODE REVIEW

**Comment by pnasrat** [comment]
Given the age of this - should this be closed?

**Comment by sergii-tkachenko** [comment]
Not sure, this still lives as phoenix vagrant 2.0.0.beta1.
https://atlas.hashicorp.com/dosomething/boxes/phoenix

**Comment by pnasrat** [comment]
I suggest this specific PR gets abandoned given the age and the fact we've been updating the ansible playbooks anyway. Re open if it's an issue.

**Comment by sergii-tkachenko** [comment]
👍

**Pull request closed without merging**
