### PR TITLE
Updates Nodejs/npm.

### LINKED ISSUE #86: Update npm to >= 2.13.1
Requested by @DFurnes 
Should fix https://jenkins.dosomething.org/job/Deploy-Staging/144/console
```
dosomething@ip-10-100-65-7:/var/www/staging.beta.dosomething.org/releases/20150723202759/lib/themes/dosomething/paraneue_dosomething$ npm install
npm ERR! 404 404 Not Found: dosomething
npm ERR! 404
npm ERR! 404 'dosomething' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
```

### PR DESCRIPTION
**Pull request by sergii-tkachenko**
Fixes #86.

```
vagrant@dev:~$ npm --version
2.11.3
```

### CODE REVIEW

**Comment by sergii-tkachenko** [comment]
Note: still testing build locally.

**Comment by sheydari-ds** [comment]
@sergii-tkachenko Just making sure we want to lock on Casper version and it won't break anything else?

**Comment by sergii-tkachenko** [comment]
Yes, we want to lock it for now.

**Comment by sheydari-ds** [comment]
Okay, looking good then, as long as your local testing works.

**Pull request merged**
